#!/bin/sh

DaySuffix() {
  case `date +%d` in
    1|21|31) echo "st";;
    2|22)    echo "nd";;
    3|23)    echo "rd";;
    *)       echo "th";;
  esac
}

SCRIPT_PATH=$(dirname "$0")

if [[ "$1" == "web" ]]; then
    cd "$SCRIPT_PATH/server" && npm start
else
    echo -e "Hello AppKu™ friends, this is Waka v$APPKU_WAKA_VERSION. Today is $(date "+%A, the %-d`DaySuffix` of %B, %Y")!"
fi