#!/bin/bash 

# Copyright AppKu
# https://github.com/appku/waka

set -eu -o pipefail

if [[ -f package.json ]]; then
    npm install --no-fund --no-audit --skip-installed --prefer-offline --dev
    if cat package.json | grep '"lint":' &> /dev/null; then
        npm run lint
    else
        echo "No lint npm script detected."
    fi
    if cat package.json | grep '"build":' &> /dev/null; then
        echo "Running npm test script."
        npm run build
    else
        echo "No build npm script detected."
    fi
    if cat package.json | grep '"test":' &> /dev/null; then
        echo "Running npm test script."
        npm test
    else
        echo "No test npm script detected."
    fi
    echo "Pruning packages to production-only."
    npm prune --omit=dev
    echo "Done."
else 
    echo "No package.json found in current directory \"$(pwd)\"."
    exit 1
fi